/* Cinta Kita v89 · first-time tutorial + shared home. Separate from expedition saves. */
(()=>{'use strict';
const $=id=>document.getElementById(id);
const client=window.supabase?.createClient('https://djhhwdjgokzofkaemrpf.supabase.co','sb_publishable_74Fr4c8T4OIKBgXED-sgsg_iUPBviG0');
const catalog={bed:{name:'Cozy bed',icon:'🛏️',cost:35},sofa:{name:'Rose sofa',icon:'🛋️',cost:28},table:{name:'Wooden table',icon:'🪵',cost:16},plant:{name:'Potted plant',icon:'🪴',cost:12},lamp:{name:'Standing lamp',icon:'💡',cost:15},rug:{name:'Soft rug',icon:'🧶',cost:18},bookcase:{name:'Bookcase',icon:'📚',cost:25},catbed:{name:'Pet bed',icon:'🐾',cost:18},flowers:{name:'Flowers',icon:'💐',cost:10},chest:{name:'Treasure chest',icon:'🧰',cost:20}};
const steps=[['Welcome to Goblin Hollow','This little practice is safe: it will not cost coins, use your potions, or change your saved expedition.'],['Turns and enemy intentions','Choose ONE action at a time. After your action, surviving enemies may respond. Read the intention under each goblin before choosing.'],['Attack and Focus','A basic Attack damages the selected enemy and recovers Focus. Focus is energy for stronger abilities; you can hold up to four. The Focus action gives +2 Focus and 5 shield, but uses your turn.'],['Skills and finishers','Your class Skill costs Focus: Knight uses Shield Break; Ranger uses Venom Arrow. Your ultimate hits all enemies and costs 3 Focus. Read the cost on each button.'],['Protect yourself','Guard gives you 12 shield and +1 Focus. Shield absorbs direct damage; poison bypasses it. Protect shields the ally chosen in the support menu.'],['Teamwork and supplies','Party actions charge a shared combo meter. When it reaches six, United Strike hits every enemy. Potions heal; Revive brings a fallen ally back.'],['Your new shared home','Open Our Home from the lobby. Create a house, share the 12-character invite code with your girlfriend, buy furniture and click an empty floor tile to place it. Both accounts share the same saved room.']];
let uid=null,home=null,selected=null,mode='place',busy=false,refreshTimer=null,requestId=0,lastHomeVersion='';
const message=t=>{$('homeMessage').textContent=t||'';};
function tutorial(show=true){if(!uid)return;if(!show){$('tutorialDialog').close();localStorage.setItem('ck89Tutorial:'+uid,'done');return;}let current=0;const dialog=$('tutorialDialog');function draw(){const [title,body]=steps[current];$('tutorialProgress').textContent=`${current+1} / ${steps.length}`;$('tutorialTitle').textContent=title;$('tutorialText').textContent=body;$('tutorialPrev').disabled=current===0;$('tutorialNext').textContent=current===steps.length-1?'Finish tutorial':'Next →';}draw();$('tutorialPrev').onclick=()=>{current=Math.max(0,current-1);draw();};$('tutorialNext').onclick=()=>{if(current===steps.length-1)tutorial(false);else{current++;draw();}};if(!dialog.open)dialog.showModal();}
function setBusy(v){busy=v;for(const e of $('homePanel').querySelectorAll('button'))e.disabled=v;}
async function fetchHome(){if(!uid||!client)return;const id=++requestId;try{const {data,error}=await client.from('cinta_dungeon_homes').select('*').or(`owner_id.eq.${uid},partner_id.eq.${uid}`).order('created_at',{ascending:true}).limit(1).maybeSingle();if(error)throw error;if(id!==requestId)return;const signature=JSON.stringify(data);if(signature!==lastHomeVersion){home=data;lastHomeVersion=signature;draw();}}catch(e){message('Home unavailable: '+e.message+' · Run the v89 housing SQL in Supabase.');}}
function draw(){const has=!!home;$('homeSetup').hidden=has;$('homeInterior').hidden=!has;if(!has)return;$('homeCoins').textContent=`🪙 ${home.coins} house coins`;$('homeCode').value=home.invite_code;$('homeMembers').textContent=home.partner_id?'Shared with your partner':'Waiting for your partner';const items=home.items||[];const tileMap=new Map(items.map(f=>[`${f.x},${f.y}`,f]));$('homeFloor').replaceChildren();for(let y=0;y<6;y++)for(let x=0;x<8;x++){const f=tileMap.get(`${x},${y}`),b=document.createElement('button');b.type='button';b.className='home-tile';b.dataset.x=x;b.dataset.y=y;b.setAttribute('aria-label',f?`${catalog[f.type]?.name||'Furniture'} at ${x+1},${y+1}`:`Empty tile ${x+1},${y+1}`);if(f){b.textContent=catalog[f.type]?.icon||'📦';b.title=catalog[f.type]?.name||'Furniture';}else b.textContent='·';b.onclick=()=>tile(x,y,f);$('homeFloor').append(b);}drawShop();}
function drawShop(){$('homeShop').replaceChildren();for(const [type,f] of Object.entries(catalog)){const b=document.createElement('button');b.type='button';b.className='shop-item';b.dataset.selected=String(selected===type&&mode==='place');b.innerHTML=`<span class="shop-emoji">${f.icon}</span><strong>${f.name}</strong><small>${f.cost} 🪙</small>`;b.onclick=()=>{selected=type;mode='place';message(`Click an empty floor tile to buy and place ${f.name} (${f.cost} coins). Click occupied furniture to move it.`);drawShop();};$('homeShop').append(b);}}
async function call(name,args){if(busy)return;setBusy(true);message('Saving your home…');try{const {data,error}=await client.rpc(name,args);if(error)throw error;const signature=JSON.stringify(data);if(signature!==lastHomeVersion){home=data;lastHomeVersion=signature;draw();}message('Saved. Your partner will see this change.');}catch(e){message(e.message||'Could not save; try again.');await fetchHome();}finally{setBusy(false);}}
function tile(x,y,f){if(busy||!home)return;if(f){if(mode==='move'&&selected&&selected.id===f.id){selected=null;mode='place';message('Move canceled.');return;}mode='move';selected={id:f.id,x:f.x,y:f.y};message(`Moving ${catalog[f.type]?.name||'furniture'}: click another empty tile. Click this tile again to cancel.`);return;}if(mode==='move'&&selected){const piece=selected;selected=null;mode='place';call('cinta_home_change_v89',{p_home:home.id,p_action:'move',p_item:piece.id,p_type:null,p_x:x,p_y:y});return;}if(!selected){message('First choose furniture in the shop.');return;}call('cinta_home_change_v89',{p_home:home.id,p_action:'buy',p_item:null,p_type:selected,p_x:x,p_y:y});}
$('homeCreate').onclick=()=>call('cinta_home_create_v89',{});
$('homeJoinForm').onsubmit=async e=>{e.preventDefault();const code=$('homeJoinCode').value.trim().toUpperCase();if(!/^[A-F0-9]{12}$/.test(code)){message('Enter a valid 12-character invite code.');return;}await call('cinta_home_join_v89',{p_code:code});};
$('homeCopy').onclick=async()=>{try{await navigator.clipboard.writeText(home.invite_code);message('Invite code copied!');}catch{message('Select the code above and copy it manually.');}};
$('homeRemove').onclick=()=>{if(mode==='move'&&selected){const piece=selected;mode='place';selected=null;call('cinta_home_change_v89',{p_home:home.id,p_action:'remove',p_item:piece.id,p_type:null,p_x:null,p_y:null});}else message('Click furniture on the floor, then click Put in storage.');};
function openHome(){if(!uid){message('Sign in first.');return;}$('homePanel').hidden=false;fetchHome();}$('homePanelOpen').onclick=openHome;const quick=$('homeQuick');if(quick)quick.onclick=openHome;const guide=$('tutorialQuick');if(guide)guide.onclick=()=>tutorial();$('homePanelClose').onclick=()=>{$('homePanel').hidden=true;};$('tutorialOpen').onclick=()=>tutorial();$('tutorialSkip').onclick=()=>tutorial(false);
function acceptUser(id){if(uid===id)return;uid=id;home=null;lastHomeVersion='';requestId++;clearInterval(refreshTimer);if(!uid){$('homePanel').hidden=true;return;}refreshTimer=setInterval(()=>{if(!$('homePanel').hidden&&!document.hidden&&!busy&&!$('homePanel').contains(document.activeElement))fetchHome();},15000);openHome();if(!localStorage.getItem('ck89Tutorial:'+uid))setTimeout(()=>{if(uid===id)tutorial();},600);}
window.addEventListener('cinta-dungeon-auth',event=>acceptUser(event.detail?.user?.id||null));
if(client){client.auth.getSession().then(({data})=>acceptUser(data?.session?.user?.id||null)).catch(()=>{});client.auth.onAuthStateChange((_event,session)=>acceptUser(session?.user?.id||null));}else message('Supabase failed to load. Refresh the page.');
})();
